### ISSUE TITLE
Banners stretch when size of browser window changes.

### ISSUE THREAD

**Issue by Hypsicratea** [ModalSeoul/Weeb.FM#12]
Banners should crop instead of stretching when the size of the browser window changes. Consider implementing something like YouTube does with channel banners as shown by this template. They recommend using a 1440p image as the channel art and then crop according to the template.
![channel art template 2](https://cloud.githubusercontent.com/assets/23017679/19631498/2eecfc28-996b-11e6-81b2-7f1c72f7db4a.png)

Hor+/- > Stretching

**Comment by ghost** [comment]
This would allow people to do neat things with their banner/profile picture

http://i.imgur.com/brbuBNC.png (Laptop)

http://i.imgur.com/r7I3Qlg.png (Desktop)
