### ISSUE TITLE
Username field is not detected by LastPass which results in only the password being autofilled

### ISSUE THREAD

**Issue by stark-reality** [ModalSeoul/Weeb.FM#14]
[http://i.imgur.com/k5VkGDa.png](url)

**Comment by Hypsicratea** [comment]
Not sure how LastPass works, but KeePass typically enters username first, then does a Tab key press, then enters password, followed by an enter key press. 
Have you tried selecting the username field before issuing the command to auto-enter the username and password?

KeePass auto-fill works fine.

**Comment by justcald** [comment]
Done
