### ISSUE TITLE
[Request] Lock the banner size to a pre-defined aspect ratio 

### ISSUE THREAD

**Issue by ghost** [ModalSeoul/Weeb.FM#18]
This would allow people to do neat things with their banner/profile picture 

http://i.imgur.com/brbuBNC.png (Laptop)

http://i.imgur.com/r7I3Qlg.png (Desktop)

**Comment by Hypsicratea** [comment]
Similar issue: https://github.com/ModalSeoul/Weeb.FM/issues/12
