### ISSUE TITLE
"Users who have scrobbled..." interference with ampersand in artist name

### ISSUE THREAD

**Issue by lapagen** [ModalSeoul/Weeb.FM#22]
**EDIT: It's an issue with the ampersand in the artist name. See link on first comment.**

User Hypsicratea has played songs by La Monte Young & Marian Zazeela, but she doesn't appear in this artist's page. There's no one under the column name on the page.

https://modal.moe/profile/Hypsicratea
https://modal.moe/artist/La%20Monte%20Young%20%26%20Marian%20Zazeela

The user scrobbled two tracks, both of which have colons in the title (_Drift Study 14 VII 73 9:27:27-10:06:41 PM NYC_ and _13 I 73 5:35 - 6:14:03 PM NYC_).

**Comment by Hypsicratea** [comment]
It is an issue with the ampersand in the artist name. Same bug occurs here: https://modal.moe/artist/Acid%20Mothers%20Temple%20%26%20The%20Melting%20Paraiso%20U.F.O.
and here:
https://modal.moe/artist/M500%20%26%203MB

**Comment by lapagen** [comment]
Edited.

**Comment by ModalSeoul** [comment]
Isn't this an issue with _only_ the Chrome extension?

**Comment by Hypsicratea** [comment]
It's an issue with the site not showing who has scrobbled artists that include an ampersand in the name, despite such scrobbles showing up on the leaderboard and on the user's profile. All such scrobbles made by me were done with RipFM.

**Comment by ModalSeoul** [comment]
Hmmm. K. Will look into it.

Thanks.

**Comment by ModalSeoul** [comment]
This is on my todo list for today.
