### ISSUE TITLE
Suggestions for cleanup of Get Started page

### ISSUE THREAD

**Issue by Hypsicratea** [ModalSeoul/Weeb.FM#23]
On the Get Started page I would suggest merging the "Ways to Scrobble" and "Scrobbler downloads" tables, arrange alphabetically, and for each entry include a link to the executable and one to the source code. Arranged as follows:

| Ways to scrobble | Download | GitHub |
| --- | --- | --- |
| Chrome Extension (Bandcamp, Google Play, Pandora) | [Link here] | [Link here] |
| Foobar2000 | [Link here] | [Link here] |
| MPD | [Link here] | [Link here] |
| MusicBee | [Link here] | [Link here] |
| RipFM (From Last.fm to Wilt) | [Link here] | [Link here] |

**Comment by shakedown-street** [comment]
Thanks for the suggestion.  This has been added (minus the github column for now).
