### ISSUE TITLE
Feature request: nullifying cheaters' data

### ISSUE THREAD

**Issue by lapagen** [ModalSeoul/Weeb.FM#36]
With plans to implement manual scrobbling directly, editing and the like (in addition to visual modifications), Wilt aims for customizability. To keep actual global statistics (unlike Last), we may need a countermeasure against obvious cheaters. There's also people who are simply not going to use the features the way they were designed for. But suspending, banning or reseting accounts would go against the philosophy, so the idea is to just nullify the data, or part of it, outside of their profiles. It could be automated or handled manually with a reporting function.

Examples of obvious cheating would be: scrobbling the same 4-minute song every minute; supposed constant scrobbling of only small parts of every song; repeatedly editing scrobbles such as to completely change the artist or song; (if we go Last's way) getting enough scrobbles to get access to all the features without scrobbling ever again; deliberately faking scrobbles to get into some top in whatever way; ...

When I say nullifying only parts of the data, I mean for instance that some user would count in an artist's total listeners count, but wouldn't in total scrobbles, or some song scrobbles. This means there'd be more than one nullifying option.

Nullified accounts would have a mention on their profiles (visible by anyone?), in the form of an icon or info somewhere, for eventual mistakes and confusion. Clicking on the icon or hovering over it would reveal which data has actually been affected. Or maybe show an alert box with all the info directly on the profile, under the avatar/header for instance.

EDIT:

Silently nullifying might be a more effective countermeasure.

This is cheating:
http://i.imgur.com/lAZh6YM.png (http://www.last.fm/user/Enigma_Machine_)
http://i.imgur.com/1fJDGg8.png this is a 4 minute song (http://www.last.fm/user/betogrinder)

**Comment by ModalSeoul** [comment]
Oh for sure. Anyone found to be anything close to that can be sure that their data *won't* be contributing towards any sort of global statistic.
