### ISSUE TITLE
Clicking on the button for the page you are already on does nothing, it should refresh.

### ISSUE THREAD

**Issue by Hypsicratea** [ModalSeoul/Weeb.FM#5]
Clicking on the button for the page you are already on does nothing, it should refresh the page.

**Comment by ModalSeoul** [comment]
This isn't something that I'm open to implementing. Someone could just endlessly click on a single button over and over again and not realize that they're potentially causing server issues(unlikely, but still).

Instead pages that would warrant refreshing will be given periodic automatic refreshing as well as a refresh button that won't reload, but simply re-fetch data.

Thanks!
Closed.
