### ISSUE TITLE
Links to the MPD, Chrome, and Spotify scrobblers need to be added to Get Started page.

### ISSUE THREAD

**Issue by Hypsicratea** [ModalSeoul/Weeb.FM#8]
Links to download the scrobblers for MPD, Chrome, and Spotify should be added to the Get Started page.

**Comment by ModalSeoul** [comment]
Spotify scrobbler is broken at the moment. Not a priority fix because RipFM is working as expected. Will fix the Spotify scrobbler by this coming Friday.

Added the rest. Thanks.

Closed.
